ALTER TABLE signups ADD COLUMN nurture_day2_sent INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE signups ADD COLUMN nurture_day5_sent INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE signups ADD COLUMN nurture_day8_sent INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE signups ADD COLUMN nurture_day12_sent INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE signups ADD COLUMN unsubscribed_at TEXT;
